config/routes.rb
Rails.application.routes.draw do


  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end
  get '/' => 'products#index'# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews

  validates :name, :description, :price_in_cents, presence: true
  validates :price_in_cents, numericality: { only_integer: true }

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :review, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index
  @products = Product.all
  
end

def create
  @product = Product.new

  @product.name = params[:product][:name]
  @product.description = params[:product][:description]
  @product.price_in_cents = params[:product][:price_in_cents]

  if @product.save
    redirect_to '/products'
  else
    render :new
  end
  flash[:notice] = "Product successfully created"
end

def new
  @product = Product.new

end

def edit
  # @product = Product.new
  @product = Product.find(params[:id])
end

def show
  @product = Product.find(params[:id])
  @review = @product.reviews.new
end

def update
  @product = Product.find(params[:id])
  @product.name = params[:product][:name]
  @product.description = params[:product][:description]
  @product.price_in_cents = params[:product][:price_in_cents]
  if @product.save
      redirect_to "/products/#{params[:id]}"
    else
      render :edit
    end
  flash[:notice] = "Product successfully updated"
end

def destroy
  @product = Product.find(params[:id])
  @product.destroy
  flash[:notice] = "Product successfully deleted"
  redirect_to "/products"

end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    @review.review = params[:review][:review]

    if @review.save
      redirect_to "/products/#{@product.id}"
    else
      render :new
    end
    flash[:notice] = "Review successfully created"
  end

  def new
    @review = Review.new
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])

  end

  def update
    p params
    @product = Product.find(params[:product_id])


    @review = Review.find(params[:id])

    @review.name = params[:review][:name]
    @review.review = params[:review][:review]

    if @review.save
        redirect_to "/products/#{params[:product_id]}}"
      else
        render :edit
      end
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      redirect_to "/products/#{params[:product_id]}}"
      flash[:notice] = "Review deleted"
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>

      <%=link_to "Homepage", products_path%>
      <%=link_to "New Product", new_product_path %>

    </nav>
    <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p class="alert"><%= flash[:alert] %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_partial.view.erb
<%= form_for @product do |f| %>
<p><%= f.label :name %>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :description %>
<%= f.text_field :description %>
</p>
<p>
<%= f.label :price_in_cents %>
<%= f.text_field :price_in_cents %>
</p>
<p>

  <%= f.submit %>
  </p>

  <%end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "partial.view.erb"%>

<%=link_to("Back to product", "/products/#{params[:id]}") %>

app/views/products/index.html.erb
<h1>Welcome</h1>

<div>
  <%=yield%>
  <%@products%>
  <p><%@products.each do |product|%>
    <ul>
    <h2><%=product.name%></h2>
    <li><%=product.description%></li>
    <li><%=product.price_in_dollars%></li>
    <li><%=link_to("Reviews", "/products/#{product.id}") %></li>
</ul>
<%end%>
<!-- <link -->

</p>

</div>

app/views/products/new.html.erb
<h1>Create a new product</h1>
<% if @product.errors.any? %>
  <div id="error_explanation">

    <h2> <%= pluralize(@product.errors.count, "error") %> because you suck!: </h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render "partial.view.erb"%>

app/views/products/show.html.erb
<h1>Look at our beautiful product</h1>
<h3><%=@product.name%></h3>
 <%=@product.description%>
 <%=@product.price_in_dollars%>
 <%=link_to("Edit", "/products/#{params[:id]}/edit") %>
 <%=link_to("Delete", "/products/#{@product.id}", method: :delete, data: {confirm: "This is a beautiful peace of jewelery. Are you sure you want to let it go?"})%>


<h2>Reviews</h2>
<ul>
  <% @product.reviews.all.each do |review| %>
  <li>
    <p>
     On <%= review.created_at %>,
   </p>
   <p><%= review.review %></p>
     <%=link_to("Edit Review", "/products/#{@product.id}/reviews/#{review.id}/edit")%>
     <%=link_to("Delete", "/products/#{@product.id}/reviews/#{review.id}", method: :delete, data: {confirm: "Are you sure you want to delete this review?"})%>
   <%end%>

 </li>
 </ul>

 <h4>New Review</h4>

  <%=render "/reviews/form.html.erb"%>

app/views/reviews/_form.html.erb
  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :review %><br />
      <%= f.text_area :review %>
    </div>
    <div class="actions">
      <%= f.submit %>
       </div>
     <% end %>

app/views/reviews/edit.html.erb
  <%=render "form.html.erb"%>